spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-demo-db
    username: postgres
    password: secretpwd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
